name: build
on:
  push:
  schedule:
    - cron: '0 10 * * *'
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest,ubuntu-latest,macos-14]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: bkaradzic/bx
        path: ./bx
    - uses: actions/checkout@v4
      with:
        repository: bkaradzic/bimg
        path: ./bimg
    - uses: actions/checkout@v4
      with:
        repository: bkaradzic/bgfx
        path: ./bgfx
    - uses: actboy168/setup-luamake@master
    - run: luamake generator
    - run: luamake
